development:
  adapter: postgresql
  encoding: unicode
  database: read_messages_from_group
  username: postgres
  password: 1234
  host: localhost
  port: 5432
  pool: 20       # <-- максимальное число соединений
  timeout: 5000 # <-- таймаут на получение соединения
